name: Auto Assign PRs to Project
on:
  issues:
    types: [ opened ]
  pull_request:
    types: [ opened ]
    
# github-script: https://github.com/actions/github-script
# -> points to github rest (octokit) reference doc

# github PAT: https://github.com/settings/tokens
# must have full repo access

# FIXME how can I prevent a user from creating a PR and stealing my token?
    
jobs:
  assign:
    runs-on: ubuntu-latest
    name: Assign
    steps:
    - name: Assign
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN_TESTREPO }}
        script: |
            //const project_id = 2
            //const column_name = 'Drafting'
            
            const project_id = 1
            const column_name = 'To do'

            // find the column
            const columns = await github.projects.listColumns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                project_id: project_id
            })
            var column = null
            for (const c of columns) {
                if (c.name === column_name) {
                    column = c
                }
            }
            if (c === null) {
                core.setFailed(`Failed to find column "${column_name}" in project ${project_id}.`)
                return
            }
            
            var content_type = null
            if (github.event.name === 'issue') {
                content_type = 'Issue'
            }
            if (github.event.name === 'pull_request') {
                content_type = 'PullRequest'
            }
            if (content_type === null) {
                core.setFailed(`Unexpected event name "${github.event.name}".`)
            }
            
            await github.projects.createCard({
                column_id: column.id,
                //note:,
                content_id: context.issue.number,
                content_type: content_type
            })
            
            /*
            await github.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                
            })
            */