
name: Experiment
on: push

jobs:

  experiment:
    name: Experiment

    runs-on: ubuntu-latest

    steps:
      - name: Experiment
        uses: zpqrtbnk/gh-actions/experiment@master
        
      - name: Infos
        shell: bash
        run: |
          echo "github.ref: '${{ github.ref }}'"
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report
        shell: bash
        run: |
          git log --graph --pretty=format':%h%%d %s %an, %ar' | head -n 5