name: Publish Release
on: workflow_dispatch
jobs:
  job:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/') # 19 leading chars
    steps:
    
    - name: Validate the release
      uses: actions/github-script@v5
      with:
        script: |
          const script = require('./.github/workflows/publish-release.js')
          console.log(script)
