name: Publish Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure repository
      shell: bash
      run: |
        git config user.email "github-actions@hazelcast.com"
        git config user.name "GitHub Actions (Build Release)"

    - name: Validate the release
      uses: actions/github-script@v5
      with:
        script: |
          const script = require('./.github/workflows/publish-release.js')
          console.log('VERSION')
          console.log(context.payload.inputs.version)
          console.log('SCRIPT')
          console.log(script)
          const f = await script({github, context, core})
          console.log('F')
          console.log(f)
          console.log('EXECUTE')
          f.test()
