name: Symlink Test
on:
  # trigger on push to any branch
  push:
    branches-ignore:
      - 'release/*'
    tags-ignore:
      - '*'

jobs:

  # try to create and push the symlink
  symlink-test:

    name: Symlink Test
    runs-on: windows-latest

    steps:

      # checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # symlink
      #- name: Symlink Bash
      #  shell: bash
      #  run: |
      #      if ! [ -L bang ]; then
      #          # however, this does *not* create a symlink, but a directory
      #          ln -s duh bang
      #          ls -l
      #          git config --global user.email "stephan@REDACTED.com"
      #          git config --global user.name "Stephan"
      #          git config --global core.symlinks "true"
      #          git add bang
      #          git commit -m "created symlink"
      #      fi

      # symlink via pwsh
      - name: Symlink Pwsh
        shell: pwsh
        run: |
          if (! (test-path bang)) {
            New-Item -ItemType SymbolicLink -Name bang -Target duh
            git config --global user.email "stephan@REDACTED.com"
            git config --global user.name "Stephan"
            git config --global core.symlinks "true"
            git add bang
            git commit -m "created symlink"
          }

      # push changes back
      - name: Push
        shell: bash
        run: git push